### ISSUE TITLE
create zip archives with files 0644

### ISSUE THREAD

**Issue by rjbs** [miyagawa/Archive-Any-Create#3]
I use this library in Module::Faker to make fake CPAN-like dists for testing.  Turns out that in zip mode, files are created 0666.  PAUSE rejects archives with files that will be world-writable, so I can't use this as-is.  Instead I'm doing this sort of daffy thing:

https://github.com/rjbs/Module-Faker/pull/14/files

Any thoughts on changing Archive-Any-Create to (a) do this chmod itself or (b) make the way I'm fiddling with the extension-to-class map supported? :)

**Comment by miyagawa** [comment]
I don't have a good answer, but the module has not been updated for literally decades and I don't expect any meaningful changes to it, so whatever you're doing seems fine and will likely be "supported" :)

**Comment by rjbs** [comment]
Works for me!
